$script:WinOptimizerRoot=$null;$script:WinOptimizerDataFolder=$null;$script:WinOptimizerBackupFolder=$null;$script:WinOptimizerLogFile=$null;$script:WinOptimizerChangesFile=$null;$script:WinOptimizerVersion="2.1.0"
function Initialize-WinOptimizer { param([string]$RootPath,[string]$AppName,[string]$Version)
 $script:WinOptimizerRoot=$RootPath;$script:WinOptimizerVersion=$Version;$script:WinOptimizerDataFolder=Join-Path $env:ProgramData $AppName;$script:WinOptimizerBackupFolder=Join-Path $script:WinOptimizerDataFolder "Backups";$script:WinOptimizerLogFile=Join-Path $script:WinOptimizerDataFolder "WinOptimizer.log";$script:WinOptimizerChangesFile=Join-Path $script:WinOptimizerDataFolder "changes.json"
 @($script:WinOptimizerDataFolder,$script:WinOptimizerBackupFolder) | ForEach-Object {if(-not(Test-Path $_)){New-Item $_ -ItemType Directory -Force|Out-Null}}
 if(-not(Test-Path $script:WinOptimizerChangesFile)){"[]"|Set-Content $script:WinOptimizerChangesFile -Encoding UTF8}
}
function Test-Administrator {$i=[Security.Principal.WindowsIdentity]::GetCurrent();$p=New-Object Security.Principal.WindowsPrincipal($i);return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Show-Header {Clear-Host;Write-Host "";Write-Host "====================================================================" -ForegroundColor Cyan;Write-Host "            WINOPTIMIZER v$script:WinOptimizerVersion - DEBLOAT EDITION" -ForegroundColor Cyan;Write-Host "              Windows Maintenance, Tweaks and Tools" -ForegroundColor DarkCyan;Write-Host "====================================================================" -ForegroundColor Cyan;Write-Host ""}
function Pause-WinOptimizer {Write-Host "";Read-Host "Pressione Enter para continuar"}
function Confirm-WinOptimizerAction {param([string]$Message);Write-Host "";return (Read-Host "$Message [S/N]") -match "^(S|SIM|Y|YES)$"}
function Write-Log {param([string]$Message,[string]$Level="INFO");Add-Content -Path $script:WinOptimizerLogFile -Value "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message"}
function Write-Status {param([string]$Message,[string]$Color="Cyan");Write-Host "[WinOptimizer] $Message" -ForegroundColor $Color;Write-Log $Message}
function Save-AppliedChange {param([string]$Category,[string]$Name,[string]$Details);$items=@();$raw=Get-Content $script:WinOptimizerChangesFile -Raw;if($raw -and $raw -ne "[]"){$items=@($raw|ConvertFrom-Json)};$items+=[PSCustomObject]@{Date=Get-Date -Format "yyyy-MM-dd HH:mm:ss";Category=$Category;Name=$Name;Details=$Details};$items|ConvertTo-Json -Depth 6|Set-Content $script:WinOptimizerChangesFile -Encoding UTF8}
function Show-WinOptimizerLog {Show-Header;Write-Host "LOG: $script:WinOptimizerLogFile" -ForegroundColor Yellow;if(Test-Path $script:WinOptimizerLogFile){Get-Content $script:WinOptimizerLogFile -Tail 100};Pause-WinOptimizer}
