function Get-DebloatConfig { $path=Join-Path $script:WinOptimizerRoot "config\debloat.json"; if(Test-Path $path){return Get-Content $path -Raw|ConvertFrom-Json};throw "config/debloat.json nao foi encontrado." }
function Set-RegistryDword {param([string]$Path,[string]$Name,[int]$Value);New-Item -Path $Path -Force|Out-Null;Set-ItemProperty -Path $Path -Name $Name -Type DWord -Value $Value -Force}
function Invoke-CommonDebloatTweaks {
    $privacy="HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy";$advertising="HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo";$cd="HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager";$explorer="HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced";$system="HKLM:\SOFTWARE\Policies\Microsoft\Windows\System";$data="HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection"
    Set-RegistryDword $data "AllowTelemetry" 1;Set-RegistryDword $privacy "TailoredExperiencesWithDiagnosticDataEnabled" 0;Set-RegistryDword $advertising "Enabled" 0
    @("ContentDeliveryAllowed","FeatureManagementEnabled","OemPreInstalledAppsEnabled","PreInstalledAppsEnabled","PreInstalledAppsEverEnabled","SilentInstalledAppsEnabled","SoftLandingEnabled","SubscribedContent-310093Enabled","SubscribedContent-338387Enabled","SubscribedContent-338388Enabled","SubscribedContent-338389Enabled","SubscribedContent-338393Enabled","SubscribedContent-353694Enabled","SubscribedContent-353696Enabled","SystemPaneSuggestionsEnabled")|ForEach-Object{Set-RegistryDword $cd $_ 0}
    Set-RegistryDword $explorer "ShowSyncProviderNotifications" 0;Set-RegistryDword $system "EnableActivityFeed" 0;Set-RegistryDword $system "PublishUserActivities" 0;Set-RegistryDword $system "UploadUserActivities" 0
}
function Remove-DebloatApps {param([string[]]$Apps,[switch]$Provisioned)
 foreach($app in $Apps){Write-Host "Removendo: $app" -ForegroundColor DarkGray;Get-AppxPackage -Name $app -AllUsers -ErrorAction SilentlyContinue|Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue;if($Provisioned){Get-AppxProvisionedPackage -Online|Where-Object{$_.DisplayName -eq $app}|Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue}}
}
function Set-OptionalServiceState {param([string[]]$Services,[string]$StartType="Disabled");foreach($service in $Services){$x=Get-Service -Name $service -ErrorAction SilentlyContinue;if($x){Stop-Service $service -Force -ErrorAction SilentlyContinue;Set-Service $service -StartupType $StartType -ErrorAction SilentlyContinue;Write-Host "Servico ajustado: $service" -ForegroundColor DarkGray}}}
function Disable-TelemetryTasks { $tasks=@("\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser","\Microsoft\Windows\Customer Experience Improvement Program\Consolidator","\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip","\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector");foreach($task in $tasks){$p=Split-Path $task -Parent;$n=Split-Path $task -Leaf;Disable-ScheduledTask -TaskPath "$p\" -TaskName $n -ErrorAction SilentlyContinue|Out-Null} }
function Show-DebloatMenu {do{Show-Header;Write-Host "DEBLOAT DO WINDOWS" -ForegroundColor Yellow;Write-Host "[1] Nivel Seguro - anuncios, sugestoes, privacidade e apps basicos";Write-Host "[2] Nivel Performance - Seguro + apps adicionais, Xbox opcional e tarefas";Write-Host "[3] Nivel Agressivo - Performance + provisionados, servicos e Cortana";Write-Host "[4] Listar apps UWP instalados";Write-Host "[5] Restaurar ajustes de Registro do debloat";Write-Host "[0] Voltar";$o=Read-Host "Opcao";switch($o){"1"{Invoke-DebloatLevel "Safe"};"2"{Invoke-DebloatLevel "Performance"};"3"{Invoke-DebloatLevel "Aggressive"};"4"{Get-AppxPackage|Sort-Object Name|Select-Object Name,PackageFullName|Format-Table -AutoSize;Pause-WinOptimizer};"5"{Reset-DebloatRegistry};"0"{break};default{Write-Host "Opcao invalida." -ForegroundColor Red;Start-Sleep 1}}}while($o -ne "0")}
function Invoke-DebloatLevel {param([ValidateSet("Safe","Performance","Aggressive")][string]$Level);Show-Header;$cfg=Get-DebloatConfig;Write-Host "DEBLOAT: $Level" -ForegroundColor Yellow;Write-Host $cfg.levels.$Level.description;Write-Host "";Write-Host "O processo cria backup de Registro e tenta criar ponto de restauracao." -ForegroundColor Yellow;if($Level -eq "Aggressive"){Write-Host "ATENCAO: Pode remover Xbox/Cortana e desativar servicos opcionais." -ForegroundColor Red};if(-not(Confirm-WinOptimizerAction "Confirmar debloat $Level?")){return};New-WinOptimizerBackup;try{New-WinOptimizerRestorePoint}catch{};try{Invoke-CommonDebloatTweaks;$apps=@($cfg.levels.$Level.apps);Remove-DebloatApps -Apps $apps;if($Level -eq "Performance"){if(Confirm-WinOptimizerAction "Voce NAO usa Xbox/Game Pass? Desativar servicos Xbox?"){Set-OptionalServiceState $cfg.xboxServices}};if($Level -eq "Aggressive"){Remove-DebloatApps -Apps $apps -Provisioned;if(Confirm-WinOptimizerAction "Desativar DiagTrack e dmwappushservice?"){Set-OptionalServiceState $cfg.telemetryServices};if(Confirm-WinOptimizerAction "Desativar Windows Error Reporting (WerSvc)?"){Set-OptionalServiceState @("WerSvc")};Disable-TelemetryTasks};Write-Status "Debloat $Level concluido. Reinicie o computador." Green;Save-AppliedChange Debloat "Nivel $Level" "Apps e ajustes do nivel aplicados."}catch{Write-Status "Debloat concluido parcialmente." Yellow;Write-Log $_.Exception.Message ERROR};Pause-WinOptimizer}
function Reset-DebloatRegistry {Show-Header;Write-Host "RESTAURAR AJUSTES DE REGISTRO DO DEBLOAT" -ForegroundColor Yellow;Write-Host "Isso remove politicas e reativa configuracoes de sugestoes conhecidas. Apps removidos devem ser reinstalados pela Store/winget.";if(-not(Confirm-WinOptimizerAction "Continuar?")){return};try{Remove-ItemProperty "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" AllowTelemetry -ErrorAction SilentlyContinue;Remove-ItemProperty "HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy" TailoredExperiencesWithDiagnosticDataEnabled -ErrorAction SilentlyContinue;Set-RegistryDword "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" Enabled 1;@("ContentDeliveryAllowed","FeatureManagementEnabled","OemPreInstalledAppsEnabled","PreInstalledAppsEnabled","PreInstalledAppsEverEnabled","SilentInstalledAppsEnabled","SoftLandingEnabled","SubscribedContent-310093Enabled","SubscribedContent-338387Enabled","SubscribedContent-338388Enabled","SubscribedContent-338389Enabled","SubscribedContent-338393Enabled","SubscribedContent-353694Enabled","SubscribedContent-353696Enabled","SystemPaneSuggestionsEnabled")|ForEach-Object{Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" $_ 1};Remove-ItemProperty "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" ShowSyncProviderNotifications -ErrorAction SilentlyContinue;@("EnableActivityFeed","PublishUserActivities","UploadUserActivities")|ForEach-Object{Remove-ItemProperty "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" $_ -ErrorAction SilentlyContinue};Write-Status "Ajustes de Registro restaurados. Reinicie o PC." Green;Save-AppliedChange Debloat "Registro restaurado" "Politicas e sugestoes restauradas."}catch{Write-Status "Restauracao parcial." Yellow};Pause-WinOptimizer}